using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Unity.Entities.Editor")]
[assembly: InternalsVisibleTo("Unity.Entities.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Entities.Hybrid")]
[assembly: InternalsVisibleTo("Unity.Entities.Hybrid.Tests")]
[assembly: InternalsVisibleTo("Unity.Scenes.Hybrid")]
[assembly: InternalsVisibleTo("Unity.Scenes.Hybrid.Tests")]
[assembly: InternalsVisibleTo("Unity.Entities.StaticTypeRegistry")]
[assembly: InternalsVisibleTo("Unity.Entities.CPlusPlus")]
[assembly: InternalsVisibleTo("Unity.DOTS.Editor")]
[assembly: InternalsVisibleTo("Unity.Authoring")]
[assembly: InternalsVisibleTo("Unity.Tiny.IO")]
[assembly: InternalsVisibleTo("Unity.Tiny.Scenes")]
[assembly: InternalsVisibleTo("TestStaticTypeRegistry")]
[assembly: InternalsVisibleTo("Unity.Entities.PerformanceTests")]
[assembly: InternalsVisibleTo("Unity.Entities.CodeGen")]
